{
 "title": "HTTP Requests",
 "tags": [
  "nestjs",
  "http",
  "requests"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Requests Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"nestjs-base-template\"} |~ `\"res\":\\{\"statusCode\"` [$__interval]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg_over_time({app=\"nestjs-base-template\"} |~ `\"responseTime\"` | json | unwrap responseTime [$__interval])",
     "legendFormat": "Response Time"
    }
   ]
  },
  {
   "title": "Response Status Codes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (statusCode) (count_over_time({app=\"nestjs-base-template\"} |~ `\"statusCode\"` | json | __error__=`` [$__range]))",
     "legendFormat": "{{statusCode}}"
    }
   ]
  },
  {
   "title": "HTTP Request Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{app=\"nestjs-base-template\"} |~ `\"req\":\\{`"
    }
   ]
  }
 ]
}